Controllers/ProductController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mendata.Net.Models;
using Mendata.Net.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace Mendata.Net.Controllers;

[Authorize(Roles = "Penjual")]

public class ProductController : Controller
{

    //    static List<ProductInput> produk = new List<ProductInput>(){
    //         new ProductInput {code = "01", nama = "laptop keren", harga = "5000", deskripsi = "laptop keren bisa gaming" }
    //     };


    private readonly ILogger<ProductController> _logger;
    private readonly dbcontext _dbContext;


    public ProductController(ILogger<ProductController> logger, dbcontext dbContext)
    {
        _dbContext = dbContext;
        _logger = logger;

    }
    [HttpGet]
    public IActionResult Index()
    {
        List<Barang> barangs = _dbContext.Barangs.ToList();
        return View(barangs);
    }

    //buat delete
    [HttpGet]
    public IActionResult Delete(int Id)
    {
        Barang br = _dbContext.Barangs.Find(Id);
        _dbContext.Barangs.Remove(br);
        _dbContext.SaveChanges();
        // List<Barang> barangs = _dbContext.Barangs.ToList();
        return RedirectToAction("Index");
    }

    //input data

    public IActionResult InputData()
    {
        //  Barang br = _dbContext.Barangs.First(x => x.Id == barangs);
        return View();
    }

    [HttpPost]
    public IActionResult InputData(RequestBarang br)
    {
        var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
        var filename = $"{br.Kode}-{br.imgname.FileName}";
        var filepath = Path.Combine(folder, filename);
        using var stream = System.IO.File.Create(filepath);
        if (br.imgname != null)
        {
            br.imgname.CopyTo(stream);
        }
        var url = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/images/{filename}";

        Barang input = new Barang
        {
            Kode = br.Kode,
            Nama = br.Nama,
            Harga = br.Harga,
            Description = br.Description,
            Stok = br.Stok,
            FileName = filename,
            Url = url,
            IdPenjual = 5
        };
        _dbContext.Barangs.Add(input);
        _dbContext.SaveChanges();
        List<Barang> data = _dbContext.Barangs.ToList();
        return View("Index", data);

    }

    //buat edit data
    [HttpGet]
    public IActionResult Editdata(int id)
    {
        Barang br = _dbContext.Barangs.First(x => x.Id == id);

        RequestBarang data = new RequestBarang
        {
            Nama = br.Nama,
            Id = br.Id,
            Description = br.Description,
            Harga = br.Harga,
            Stok = br.Stok,
            Kode = br.Kode
        };
        return View(data);
    }

    [HttpPost]
    public IActionResult Editdata(RequestBarang br)
    {
        var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");

        var filename = $"{br.Kode}-{br.imgname.FileName}";
        var filepath = Path.Combine(folder, filename);
        using var stream = System.IO.File.Create(filepath);
        if (br.imgname != null)
        {
            br.imgname.CopyTo(stream);
        }
        var url = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/images/{filename}";

        Barang updated = _dbContext.Barangs.First(x => x.Id == br.Id);

        var Deletedfilepath = Path.Combine(folder, updated.FileName);
        System.IO.File.Delete(Deletedfilepath);

        updated.Kode = br.Kode;
        updated.Harga = br.Harga;
        updated.Nama = br.Nama;
        updated.Stok = br.Stok;
        updated.Description = br.Description;
        updated.Url = url;
        updated.FileName = filename;
        _dbContext.SaveChanges();
        return RedirectToAction("Index");
    }

    // [HttpPost]
    // public IActionResult UploadFoto(RequestBarang br)
    // {
    //     var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
    //     var filename = $"{br.Kode}-{br.imgname.FileName}";
    //     var filepath = Path.Combine(folder, filename);
    //     using var stream = System.IO.File.Create(filepath);
    //     if (br.imgname != null)
    //     {
    //         br.imgname.CopyTo(stream);
    //     }
    //     var url = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/images/{filename}";

    //     Barang input = new Barang
    //     {
    //         Kode = br.Kode,
    //         Nama = br.Nama,
    //         Harga = br.Harga,
    //         Description = br.Description,
    //         Stok = br.Stok,
    //         FileName = filename,
    //         Url = url,
    //         IdPenjual = 5
    //     };
    //     _dbContext.Barangs.Add(input);
    //     _dbContext.SaveChanges();
    //     List<Barang> data = _dbContext.Barangs.ToList();
    //     return View("Index", data);

    // }




    // [HttpPost, ActionName("Delete")]
    // [ValidateAntiForgeryToken]
    // public async Task<IActionResult> DeleteConfirmed(int id)
    // {
    //     var Barang = await _dbcontext.Barang.FindAsync(id);
    //     _dbcontext.Transactions.Remove(Barang);
    //     await _dbcontext.SaveChangesAsync();
    //     return RedirectToAction(nameof(Index));
    // }



    // [HttpDelete]
    // public IActionResult Delete(int id)
    // {
    //     _dbContext.Destroy(id);
    //     return Ok(new { message = "User deleted" });
    // }


    // [HttpDelete]
    // [ProducesResponseType((int)dbcontext.NotFound)]
    // [ProducesResponseType((int)dbcontext.NoContent)]
    // public async Task<IActionResult> Delete(int id)
    // {
    //     var existingItem = await dbcontext.Customer.SingleOrDefaultAsync((System.Linq.Expressions.Expression<System.Func<Customer, bool>>)(x => x.Id == id));
    //     if (existingItem == null)
    //     {
    //         return NotFound();
    //     }

    //     dbcontext.Customer.Remove(existingItem);
    //     await _dbcontext.SaveChangesAsync();
    //     return NoContent();
    // }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Controllers/UserController.cs
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Mendata.Net.Models;
using Mendata.Net.Models.Entities;
using Mendata.Net.Models.Request;

namespace Mendata.Net.Controllers;

public class UserController : Controller
{
    private readonly dbcontext _dbContext;

    private readonly ILogger<UserController> _logger;

    public UserController(ILogger<UserController> logger, dbcontext dbContext)
    {
        _dbContext = dbContext;
        _logger = logger;

    }
    [HttpGet]
    public IActionResult IndexPenjual()
    {
        List<Penjual> penjuals = _dbContext.Penjuals.ToList();
        return View(penjuals);
    }

    //buat delete data Penjual
    [HttpGet]
    public IActionResult DeletePenjual(Penjual pj)
    {

        Penjual deleted = _dbContext.Penjuals.First(x => x.Id == pj.Id);
        _dbContext.Penjuals.Remove(deleted);
        _dbContext.SaveChanges();
        List<Penjual> penjuals = _dbContext.Penjuals.ToList();
        return View("IndexPenjual", penjuals);
    }

    //input Data Penjual
    [HttpGet]
    public IActionResult InputPenjual()
    {
        return View();
    }

    [HttpPost]
    public IActionResult InputPenjual(Penjual pj)
    {
        try
        {
            // produk.Add(pr);
            pj.IdUser = 1;
            _dbContext.Penjuals.Add(pj);
            _dbContext.SaveChanges();
            List<Penjual> penjuals = _dbContext.Penjuals.ToList();
            return View("IndexPenjual", penjuals);
            // return View("Index");
        }
        catch
        {
            return View("IndexPenjual");
        }

    }

    //buat edit 
    [HttpGet]
    public IActionResult EditPenjual(int id)
    {
        Penjual pj = _dbContext.Penjuals.First(x => x.Id == id);
        return View(pj);
    }

    // [HttpPost]
    // public IActionResult EditPenjual(Penjual pj)
    // {
    //     try
    //     {
    //         Penjual updated = _dbContext.Penjuals.First(x => x.Id == pj.Id);
    //         updated.NamaToko = pj.NamaToko;
    //         updated.AlamatToko = pj.AlamatToko;
    //         updated.NoHP = pj.NoHP;
    //         _dbContext.SaveChanges();
    //         return RedirectToAction("IndexPenjual");
    //     }
    //     catch
    //     {
    //         return View();
    //     }

    // }
    // BUAT PEMBELI YGY

    public IActionResult IndexPembeli()
    {
        List<Pembeli> pembelis = _dbContext.Pembelis.ToList();
        return View(pembelis);
    }

    //buat delete 
    [HttpGet]
    public IActionResult DeletePembeli(Pembeli pb)
    {

        Pembeli deleted = _dbContext.Pembelis.First(x => x.Id == pb.Id);
        _dbContext.Pembelis.Remove(deleted);
        _dbContext.SaveChanges();
        List<Pembeli> pembelis = _dbContext.Pembelis.ToList();
        return View("IndexPembeli", pembelis);
    }

    //input 
    [HttpGet]
    public IActionResult InputPembeli()
    {
        return View();
    }

    [HttpPost]
    public IActionResult InputPembeli(Pembeli pb)
    {
        try
        {
            // produk.Add(pr);
            pb.IdUser = 1;
            _dbContext.Pembelis.Add(pb);
            _dbContext.SaveChanges();
            List<Pembeli> pembelis = _dbContext.Pembelis.ToList();
            return View("IndexPembeli", pembelis);
            // return View("Index");
        }
        catch
        {
            return View("IndexPembeli");
        }

    }

    //buat edit 
    // [HttpGet]
    // public IActionResult EditPembeli(int id)
    // {
    //     Pembeli pb = _dbContext.Pembelis.First(x => x.Id == id);
    //     return View(pb);
    // }

    // [HttpPost]
    // public IActionResult EditPembeli(Pembeli pb)
    // {
    //     try
    //     {
    //         Pembeli updated = _dbContext.Pembelis.First(x => x.Id == pb.Id);
    //         updated.NamaPembeli = pb.NamaPembeli;
    //         updated.AlamatPembeli = pb.AlamatPembeli;
    //         updated.NoHP = pb.NoHP;
    //         _dbContext.SaveChanges();
    //         return RedirectToAction("IndexPembeli");
    //     }
    //     catch
    //     {
    //         return View();
    //     }

    // }

    //BUAT USER
    public IActionResult Login()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Login(LoginRequest login)
    {
        if (!ModelState.IsValid)
        {
            return View(login);
        }

        var user = _dbContext.Users.FirstOrDefault(x => x.Username == login.Username);

        if (user == null)
        {
            ViewBag.ErrorMessage = "Invalid Username or Password";
            return View(login);
        }

        if (user.Tipe == "Pembeli")
        {
            ViewBag.ErrorMessage = "You're not admin or seller";
            return View(login);
        }

        var claims = new List<Claim>{
            new Claim(ClaimTypes.Name,user.Username),
            new Claim("Fullname",user.Username),
            new Claim(ClaimTypes.Role,user.Tipe)
        };

        var claimsIdentity = new ClaimsIdentity(
            claims, CookieAuthenticationDefaults.AuthenticationScheme
        );

        var authProperties = new AuthenticationProperties()
        {
            ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(20),
        };

        await HttpContext.SignInAsync(
            CookieAuthenticationDefaults.AuthenticationScheme,
            new ClaimsPrincipal(claimsIdentity),
            authProperties);

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();

        return RedirectToAction("Login");
    }

    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Register(RegisterRequest request)
    {
        if (!ModelState.IsValid)
        {

            return View(request);
        }

        var newUser = new Models.Entities.User
        {
            Username = request.Username,
            Password = request.Password,
            Tipe = request.Tipe
        };

        var penjual = new Models.Entities.Penjual
        {
            IdUser = newUser.Id,
            Alamat = request.Alamat,
            NamaToko = $"{request.FullName} Store",
            User = newUser
        };

        _dbContext.Users.Add(newUser);
        _dbContext.Penjuals.Add(penjual);

        _dbContext.SaveChanges();

        return RedirectToAction("Login");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Product</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RAS.Bootcamp.MVC.NET.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eccomerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.IsInRole("Penjual"))

                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Data
                                    Produk</a>
                            </li>

                        }

                        @if (User.IsInRole("Admin"))

                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Penjual" asp-action="Index">Data
                                    Penjual</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pembeli" asp-action="Index">Data
                                    Pembeli</a>
                            </li>
                        }
                    </ul>

                    <a class="btn btn-danger" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; By Daffa <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>