Models/Entities/Pembeli.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mendata.Net.Models.Entities;

public class Pembeli
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    [ForeignKey("User")]
    public int IdUser { get; set; }
    public string? Alamat { get; set; }
    [StringLength(15)]
    public string? NoHp { get; set; }
    public virtual User? User { get; set; }
}

Controllers/PembeliController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Mendata.Net.Models;
using Mendata.Net.Models.Entities;

namespace Mendata.Net.Controllers;

public class PembeliController : Controller
{
    private readonly ILogger<PembeliController> _logger;
    private readonly dbcontext _dbContext;

    public PembeliController(ILogger<PembeliController> logger, dbcontext dbContext)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    public IActionResult Index()
    {
        List<Pembeli> pembelis = _dbContext.Pembelis.ToList();
        return View(pembelis);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Pembeli pem)
    {
        try
        {
            pem.IdUser = 1;
            _dbContext.Pembelis.Add(pem);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    [HttpGet]
    public IActionResult Update(int id)
    {
        Pembeli pem = _dbContext.Pembelis.First(x => x.Id == id);
        return View(pem);
    }

    [HttpPost]
    public IActionResult Update(Pembeli pem)
    {
        try
        {
            Pembeli updated = _dbContext.Pembelis.First(x => x.Id == pem.Id);
            updated.Id = pem.Id;
            updated.Alamat = pem.Alamat;
            updated.NoHp = pem.NoHp;
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    [HttpGet]
    public ActionResult Delete(int id)
    {
        Pembeli pem = _dbContext.Pembelis.Find(id);
        _dbContext.Pembelis.Remove(pem);
        _dbContext.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

Views/Pembeli/Create.cshtml
@using System.Collections;
@model Mendata.Net.Models.Entities.Pembeli
@{
    ViewData["Title"] = "Create Page";
}

<div class="text-center">
    <h1 class="display-4">Create Pembeli</h1>
</div>
<form action="Create" method="post">
    <div class="mb-3">
        <label for="Nama" class="form-label">Id</label>
        <input type="text" class="form-control" id="Nama" asp-for="Id" placeholder="Masukkan Id Anda">
    </div>
    @* <div class="mb-3">
        <label for="Nama" class="form-label">Id User</label>
        <input type="text" class="form-control" id="Nama" asp-for="IdUser" placeholder="Masukkan Id User Anda">
        </div> *@
    <div class="mb-3">
        <label for="Alamat" class="form-label">Alamat</label>
        <input type="text" class="form-control" id="Alamat" asp-for="Alamat" placeholder="Masukkan alamat">
    </div>
    <div class="mb-3">
        <label for="NoHp" class="form-label">No Handphone</label>
        <input type="text" class="form-control" id="NoHp" asp-for="NoHp" placeholder="Masukkan no handphone">
    </div>
    @* <div class="mb-3">
        <label for="Negara" class="form-label">Negara Pembeli</label>
        <input type="text" class="form-control" id="Negara" asp-for="User" placeholder="Masukkan Negara Pembeli">
        </div> *@
    @* <div class="mb-3">
        <label for="ImagePembeli" class="form-label">Select Image</label>
        <input class="form-control" type="file" id="ImagePembeli">
        </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-outline-primary" asp-controller="Pembeli" asp-action="Index">Back</a>
</form>

Views/Pembeli/Index.cshtml
@using System.Collections;
@model List<Mendata.Net.Models.Entities.Pembeli>
@* @model IEnumerable<Mendata.Net.Models.Entities.Pembeli> *@
@{
    ViewBag.Title = "List Pembeli";
}

<h2 class="text-center">Data Pembeli</h2>

<table class="table table-striped mt-5">
    <thead>
        <tr>
            @* <th scope="col">No</th> *@
            <th scope="col">Id</th>
            <th scope="col" class="text-center">IdUser</th>
            @* <th scope="col" class="text-center">Nama Toko</th> *@
            <th scope="col" class="text-center">Alamat Pembeli</th>
            <th scope="col" class="text-center">No HP</th>
            <th scope="col" class="text-center">Action</th>
        </tr>
    </thead>
    <tbody class="table-light">
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    @* <td>@item.IdPembeli</td> *@
                    <td>@item.Id</td>
                    <td>@item.IdUser</td>
                    <td>@item.Alamat</td>
                    <td>@item.NoHp</td>
                    @* <td>@item.NegaraPembeli</td> *@
                    <td class="text-center">
                        <a class="btn btn-success" asp-route-id="@item.Id" asp-controller="Pembeli"
                    asp-action="Update">Update</a>
                        @* <a class="btn btn-warning" asp-route-id="@item.Id" asp-controller="Pembeli"
                            asp-action="Detail">Detail</a> *@
                        <a class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Pembeli"
                    asp-action="Delete">Delete</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <h1>Data Pembeli null</h1>
        }
    </tbody>
</table>

<div class="col">
    <a class="btn btn-primary" asp-action="Create" asp-controller="Pembeli">Tambah Pembeli</a>
</div>

Views/Pembeli/Update.cshtml
@using System.Collections;
@model Mendata.Net.Models.Entities.Pembeli
@{
    ViewData["Title"] = "Update Page";
}

<div class="text-center">
    <h1 class="display-4">Update Pembeli</h1>
</div>
<form action="Update" method="post">
    <div class="mb-3">
        <label for="Id" class="form-label">Id</label>
        <input type="Int" class="form-control" id="Id" asp-for="Id" placeholder="Masukkan Id">
    </div>
    <div class="mb-3">
        <label for="Alamat" class="form-label">Alamat Pembeli</label>
        <input type="text" class="form-control" id="Alamat" asp-for="Alamat" placeholder="Masukkan Alamat">
    </div>
    <div class="mb-3">
        <label for="NoHp" class="form-label">No Handphone</label>
        <input type="text" class="form-control" id="NoHp" asp-for="NoHp" placeholder="Masukkan No Handphone">
    </div>
    @* <div class="mb-3">
        <label for="Negara" class="form-label">Nama User</label>
        <input type="text" class="form-control" id="Negara" asp-for="User" placeholder="Masukkan Nama User">
        </div> *@
    <input type="hidden" asp-for="Id">
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-outline-primary" asp-controller="Pembeli" asp-action="Index">Back</a>
</form>